host: 127.0.0.1
port: 6606

servers:
  - identifier: dsijubhdfgbgfdnghf2
    secret: oHryZnDM8gXHfpqj
    script: /etc/gowebhook/auto_build.sh
    requestUrl: /auto_build
  - identifier: dsijubhdfgbgfdnghf
    secret: oHryZnDM8gXHfpqj1
    script: /etc/gowebhook/auto_build.sh
    requestUrl: /auto_build